zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "49181:2181"
    - "22"
nimbus:
  image: wurstmeister/storm-nimbus
  ports:
    - "49773:3773"
    - "49772:3772"
    - "49627:6627"
    - "22"
  links:
    - zookeeper:zk
supervisor:
  image: wurstmeister/storm-supervisor
  ports:
    - "8000"
    - "22"
  links:
    - nimbus:nimbus
    - zookeeper:zk
stormui:
  image: wurstmeister/storm-ui
  ports:
    - "49080:8080"
    - "22"
  links:
    - nimbus:nimbus
    - zookeeper:zk
nginx:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - stormui:stormui
  volumes:
    - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/conf/proxy_conf:/etc/nginx/conf.d/proxy_conf
    - ./nginx/certs/dockervm.crt:/etc/nginx/certs/dockervm.crt
    - ./nginx/certs/dockervm.key:/etc/nginx/certs/dockervm.key
    - ./nginx/auth/.htpasswd:/etc/nginx/.htpasswd
